### ISSUE TITLE
Why charset inside mediaType?

### ISSUE THREAD

**Issue by AlexYegupov** [killmenot/parse-data-url#1]
[Maybe](https://en.wikipedia.org/wiki/Data_URI_scheme#Syntax) they should be different fields? 

// Valid
var parsed = parseDataUrl('data:image/svg+xml;charset=UTF-8,some-data'); 
// {
//    mediaType: 'image/svg+xml',
//    charset: 'utf-8',
//    base64: false,
//    data: 'some-data'
// }

**Comment by killmenot** [comment]
@AlexYegupov 

Per [rfc2397](https://tools.ietf.org/html/rfc2397#section-4)

```
A data URL scheme's media type specification can include other parameters;
for example, one might specify a charset parameter.
```

```
  data:text/plain;charset=iso-8859-7,%be%fg%be
```

Also, please take a look: https://en.wikipedia.org/wiki/Media_type#Naming

Only by these reasons
