### ISSUE TITLE
filename support

### ISSUE THREAD

**Issue by mnlbox** [killmenot/parse-data-url#4]
Hi,
If your library support filename?
for example for this data:
```
 "image": "data:image/png;name=13.png;base64,iVBORw0KGgoAAAANSUhEUgAAAvoAAAA6CAIAAABOCmofAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3.....
```
I need to get filename and file base64 content separately is it possible?
for example I need get **13.png** and **iVBORw0KGgoAAAANSUhEUgAAAvoAAAA6CAIAAABOCmofAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3.....** in above data.

**Ref**: https://github.com/mozilla-services/react-jsonschema-form/issues/861

**Comment by killmenot** [comment]
@mnlbox I believe you're talking about `parameter`, `attribute` and `value` from here?

```
dataurl    := "data:" [ mediatype ] [ ";base64" ] "," data
mediatype  := [ type "/" subtype ] *( ";" parameter )
data       := *urlchar
parameter  := attribute "=" value
```

is it correct?

**Comment by mnlbox** [comment]
@killmenot Yes I think **name=13.png** is a parameter in above example. :thinking: 
Can we parse it now?

**Comment by killmenot** [comment]
It's not supported right now but I think I may consider to add it

**Comment by mnlbox** [comment]
Thanks. Have you any estimation for this?

**Comment by killmenot** [comment]
I cannot promise anything here now

**Comment by killmenot** [comment]
@mnlbox I rework multiple media type parameters logic. It should work now. In you case, `parsed` object will contain `name` property with value `13.png`. `mediaType` property will be `image/png;name=13.png` but you can use a new property `contentType` to get `image/png`

**Comment by mnlbox** [comment]
@killmenot Thanks man

**Comment by mr-ranga** [comment]
@killmenot  I am not getting "name" property in data. Can you please help me here, how to get file name.

"data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAPMAAADPCAMAAAAXkBfbAAAAkFBMVEX////8/Pz5+fkAAAD29vbx8fHv7+/z8/Ps7OzLy8vm5ubf39+zs7Pp6enOzs7Z2dnAwMCrq6uBgYFsbGx1dXXNzc2Tk5O6urrDw8OkpKSdnZ2MjIzV1dWHh4dISEhlZWVWVlZ7e3tBQUE1NTUrKysjIyNbW1tSUlJCQkI6OjpmZmYoKCgwMDAZGRkSEhIcHBx21hobAAAQXElEQVR4nO1dB0PjPA+WHGfvQfZoKU0px3H//999ctIJaSl3UMr7+TmuK4ljWbKWRwAkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQuAYIGtaOr312Pq0IFZxH7312LqwK59+zVwXdX44pA+t83cGcC4nfX5YrIZgY49kj+/wUQcEY8Li2O/Lvr8hf4IJ+2pzsxAGvYT6T4r0B92FjdAZjOT5RsqvyHzc2gtZyY61DZX1Clr4eerCxkH+LWcPIiB1QTYF9Tq69F8OwbH5PPgc1Zh6S1w6+p05eCtG9X8LuPmVg6G1mfI1NTG38enxnWrWZ9zK9AQae5ENem7112iwqOQZeCHQDqflFVpnvpZSwuiJzIPHWCoBWRLLdrfE5FPxHcXvjANAieXprCSYtLa2j9simsit8TbJ529b9W8bPBoHiiNz19GetmF5dcRbJdRuSKNGfiC9EBuDOrLLxUdq4F5q4yQCNRQp0z1AFC95IuiNA6AHV85lwOLO/i/BY7tPdgMIgUB3SdCVpy84JaMvAXxL30ZG8eSo7bOyb69KfVdexIjCToX0pFSCvi7Uu2/Y558L6TQf5Lk5JdryabBwdTVsdt9vlWjInCSSIZGLbpZIFnfbwMxHUA1n2yvZRBWF/AZ85nGWj96xvi+EcVs5tVqcPHfLuLqiteNQZ22sapk+dBUVrUiy6+z3Ci/WyBo/jbEnWYX6K4eb2kDlFOCphO/vt8HRnwJREmNShDv38shiQc3V8rLzY1wwV0SRIBv282P9B3e37BlRyKRPy95aOQaj9aJjV8kRtOd7SidSjIRI6ib0Ndfsxz5msTPCXffWXlJf4z8j43Z/6E6HKwquckF/X5Ai6PktlG9tC2I9fozU0/lHmtnxGc1tgWydXuIqVgzYxFOEEyqcRl5zMQAvi5fXnos4wztVzWbxxaa65+oIWbiPzHbnMBV6F8xyUZAgqE7DF+faLQXFapJF8WTgu+6jxZ+ewNzeg4l5ej9+RIdcmmCMb999iM40ujzPU9I3HsW1b5nHxpDpRIjlrG4O09sLm8qesHUq/tVm1xTKYE9giDZrJ+9xYe9CEkd0aNFm2NY8j1NSCN1cdD+fiG02Z6WRl0cZnQy2qnqsvoAm2rIpuTgRN+6qYuwh5XL7HwvflXeprYdAafNPrIossYTdeuQnrt4k1/vpv577sRCGqlpKDtBYyR4lz0gfDWET7fD9nf2CF/F4cs62vhpmOXxUak5F9ELNWvNnq7z7jwKN6Bv4rX/kH6jGP5MKvZF8cS1HvuFvaJm1ATWMkgoScrgWNAD+DMyFd3qxcRVnCehKKvsP1ZxxDhAkXb2XNh9+p4I0G4nS7nXx8hI3LeFicjC4paO39L2Al4Q6Whi0Dluf1QinOzZCB4R/Mo8PtChNUF8z7JMEsHcWDUo/3qV+J9Zuh0Cgyb+Kwspdl5mp21J06wH+jND7BZEH1oC/3DB7ujGYbGh05zqCEFaTm5aRgLX41TG9jRczzojivEyJnQmyePIqNYHias2A6rhSWoc17opMKF+lc2ECdEW3UdJ3QcJ3ACS4jzxssD0dJehsLRtWe2IJ8FybqpcWOxvxpsVoB++jAFmPdnXTFT6YSvhhE1jRmITF6rjk1kBE3q2Rr1W9Dr0h9p8cd7IYsLKyTnI4xFO2TdKrVFKItvreUXoOzU0yQPnWtln6tFqpTUIVGbBRSJif5r/R4a0QqJqo16I5fjLho+mtXQgAyc3i2FJEclWM79KiPhvlpq21ifTckIRPmpI0SO2v8e3PRc8fTSHjp+uvTAKKLiyJVl967I6fYWGWPR39uyTMUUkocwjKt3q/B5EExM3xsiIhpORoRUgNvONHFSteLFpurGw9xLQ1LGRwX3wgZlc3Bj8sLZUztPBMfNZZobgw67GjSrNd+l2WnOHPaX4cDNl9IL2ZBgIrdCSVQRZByd2FG0ghQMewsdraQhdjPOoRKuqnHdMWcnwXf6EUJwLtuRvQz+jK/MQxUG+8TTqG/dN2mlGZk8i/yPbFGnbYXDqATTuzFuu+YcElwF76hJOprPT1YJSQUOxwolUkfnypuVmqU88VfnacKK1wljTV/NTVV402TN7LU93uNaRDPh7hpwzjgM5tRMXoV0ew+FQUVuF/Pu2nY0wHrai1RnoByHY4zMtopQV27e4qaMoejuq13rV6CbNdX5UwZa614XorilW+gmPr5T9NPPXXDiTnGGDmzOk0HCWaIchWMkDy1dphdRb+6DJYTiwkj188BZ+56VEPXzekN41MzQt+zZ1ppBWQZNUfFAqUU7FLOQj+3kP/faYTHaozPEEZZxJFZRBtcFote+byPIj5hxtS7nq36e1jufGcfAiPqGTb51tCDlZTUze6etTeVgMJlckEdtV94ebGVdeQCKQ3HOCo0g7erdF3Ff1RrXzeruIEoA1BNnzKbNKqEbGpeCyO0JT8o+KER4LKb6rd2jet1pf4hJdokGSV+eHOEIEz1Bp8JWB+mGmOszOFu1cgdeGw4h41Zy7F+rfW4nXxkjbZuBsc1JwbW7M/Wup9N5H9y+WdWLiDX1MeSdB5sUAdGfBIk1RkppaxX3GTA4FN1QCfnGk7f6ArY68LCRS59dewKJ0Z9O2Y9VIxdillTzIUWnOSTJaTlWnpVRmJYilyt8i1k/v38z6qqtnu2RICwXk54Wa67cm0WYn5wfhEMwKtK3kQgGQJ/PvKIIS8FZ29VXQ3cVVzO0fv/uLHhDVqZEG41nT8uT+4Hk+Wehjs7mFYnkbkVhr5gEQFYpdqkJyLvWSZHP7SjaRf8kxbE+1XgzxYWzHs/kVV8LovnscbvvbCJx4ZE8GzNLUEu+BwbRXdGW2kYfIYWTD/5k9qhQthHZJo6+AfjNWZqdVSJq6i5sktu5M3xWTLWK7oCpewVtPCmbKQLHUsPAWt+/b4mu3BR2xSd0y9YW5etqICxfU6+3ZwNJtpJGzcDhfWYr+qN4+JaR5K3qsXI2xXJwu2sB3WQq6T66WZgtNsaznNGLUw1ZvbKr6wMpFua4uU9+n4p/S+XWJnAynnjTzSwy9C/VRit3BfkQdCZFFvzhlabVsVnryfwUs8yX+OamoDvldJIEmfmSCsNLfovaUsOoczLFOjgL/SjS5eCsfVfJ39qpEfaSIo3b0F1bqOrkoLYI/H8lYkhYpD1rhfSVH3FEQyW3+riNvIccwsWpYWZ0f81ub36mV/iW/ZpJjEiZjRMQyDEOV/TTXTOY6Ef1kGvUHmvqr8kcT423uA+tdStGagsEPwidHSu2PNTaxY7/OC9hoJlxv92FJBuV3ZKHxtfOtE6gSNr69Wjf4HopMaq/+zy+8mTpbWkjknLB+DkDu20OMhxDElhkluwHf3I0S5Ba/1mdGxf6VhxXq1SyLcsZ1muR6DISr37sEQ9GPDhka1/M5F3xE+LLwFGOsiW3i1yJdh4VQpUMWQGnmpfuEELC9oj7GIqv8xMpNWTII+VJv3Ks+BdgoC17d5fwQ2zHlD2KUHjPUJEHnMdihFVf5TAdA5PvuVLKWxXtQ6jJsw/qrqL2YhBnHFPQyPcd2lyKeZ1o36tselSAQfZbsXcJtFsFMSxUAj7Mah5/KZLjGm+/qHon9DkHsz9BEZU1V9qji24SZLt+dfoBZ7TZdFiPkP0ZcyzF9LTrwcr/fvmGpMAHQd24/3U0vcF7VidJ4upsGE8mexVY01qKsbnSnxnMvxEI4yIkdmuoEcoEp6pNgeZy01PDu9Sedtqz5fLaGfu/gX2/YipuZ3Ug6K15Inx4bHAc1XCeJkf5KNReKdHtsxmgouh/O6tJEGLOTgzUWr83813ADo2Jc+hgq9yuD7aBqJ2hNPs1AILqp+wEm9N2b84mCGPIQmV5d+Mae0C82EcE4s1r+WRuD7A/OwChkWJ4Wd6+zham9qU4DII4VOEJF8taeGeyxLqwZEp5+zwWGbtn44ipFoVNOMln/0U/40eL1lPeH/37fojZTs6B0SHFVBSbI28Q/DlTELJCef4Bgi0wa4eZW5tvjKkre5rLZKDuT6snMurKg3l2UuxtgBStf5yXpapXJ/us83jiAKrgJsrsZ2waxCG5P0rlcf/ptHkNnid/FgrQWyvlz8gTgF7/OTA/IqlXngoeCPVSm5AB+kkrlw8OTvuitwYGqbJfTC0MlB2fWbqst289aeGN1b0SGz/BExngruP9F1HnyDk3w1kMzB5BXOJXCrXF9abn/isy5YBzpHS17ux6PfYnfM1OrXj+U1qojxOHbi/Be4gxbduvdoMsw/hFrw/zVU9eEyyPvE9mRMtf5e2NWZzAmOFTqv0cKI7oTK9GPrjGbBN/E3+4XtEtV8WptTu3ClMJdhEUY6gm7y9otap2laRh2Dw9vjymnnHr8vwG0dpmB6nryNykDU6DCfsWlhWRbQ4N9MMoJtsT71dVI4Yp2yR3z2KX92VwrQUznwYEe10crEG1I+2ihV3bSRjsp9GMQkxNxdqtekNr/jM3LvsIUEzwGv2PYQJ5Ffy0rvlXSF/2n4OC/wx/+Z/AoFpt7TR46c/pl38PIjTtNx+hTv9i/5kfB6GitzSTyvZfr9r9b0IHZz3Ogcob4z9P7Qiyz3+GVath+ZHdSH4yRLpu3nq6kxT/fZk+xHy1Ko0f5zP/G1A9mJ38fwI8migmISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISFxJVw6X/8f5vXf1JKA/aO5DQbaq90A9cNFKnfnihkvVP2aA/NMm4Fl1hq4ta9hbXo5U2tP7Ilg+QzpMNd9z2fgmXf1dzTGdjMHHRxb/O0hdmbNJ87cHX0L1+lt0J28uoN5XpRQhaEDXl52mBVBqYNbJTrL8irXnTDNwTSHB1pdE2YUBTArGgciwFSN07BLTbOoQsiq0AvTtC5jx0ybgmlFU2oJho4KYJdNwYuy8mBeVmkRjbvQWJudWcQu1sjSnMVWXlodWJ0mFmWKZ7JGNguDhtPhUuwc64h9+Ypr71TkOJxBZ2gRsRBjKG1IVSzDPOFhBkbjczADcDxW+kHIxKPHMvGIwTBAsCLXb6BzrYTXw5aC2q94JDrRxONBGx+KhtouDZ2eAa9qIjvrbM9hjQ5+2tTUSI0ndgxwz9bw82EHpSMkthMvMaQuNFyPfd/E0AdmhpUa5FD6RLYjdgF8GrbvRvH8QLG0NKZ/PAF32EZLfe5Gmsed1oNCbUCLdNW3O0YSzVC3/civ4mrlDIeBi2d3gllduztbVlBiB/AEjWWvIAxYaeqVqZtANHPbSuu7UHVCq7HMyjagUyvT9tApXctI/DCkttJjcMdnIG+WvtuRxwxfjzI9trIUbavMcHg0qebmJETMSDTXVpsMYsfQAedX357JLEhnUX0ccMO8AN/J7dBUhdqpDaD3DA3H0bPCRDSLTHfAzj0T9CDMwStCUnrAAvp6sLmckaWFrZdFoMGdKDwoSAOg2PXBLkMhJTxgVlEGqlqU5R2y4Nv2ONnt77n/ZUrkTu1ae/7QIdjEb9+Pk4tGpzdXH14ve1I1Tnz8scvaXlOMJ36X+Gf8D3anwKd2U9DtAAAAAElFTkSuQmCC"

**Comment by mr-ranga** [comment]
this is json 

{
      "type": "flex",
      "flex-flow": "row wrap",
      "items": [
        {
          "key": "newSignatures",
          "type": "array",
          "items": [
            {
              "type": "flex",
              "flex-flow": "row wrap",
              "items": [
                {
                  "key": "newSignatures[].sigText",
                  "flex": "0 0 45%",
                  "type": "file",
                  "acceptFileTypes": "image/*"
                },
                {
                  "key": "newSignatures[].sigText",
                  "flex": "0 0 30%",
                  "type": "image"
                }
              ]
            }
          ]
        }
      ]
    }
